### ISSUE TITLE
Design the client API 

### ISSUE THREAD

**Issue by vsamtuc** [stelar-eu/stelar_client#1]

**Comment by petroud** [comment]
Designed and Implemented a structure for the client. The implementation incorporates a flexible skeleton for adding more and more methods mapping to one or more endpoints each. The Client consists of 4 major operators :

1. The Workflow Operator, responsible for executing and managing workflow/task executions
2. The Catalog Operator, responsible for managing resources in the catalog with all CRUD features.
3. The Knowledge Graph Operator, responsible for accessign query endpoints that perform search tasks on the KG.
4. The Administration Operator, responsible for providing features realted to user management, token & auth management etc.
